fix: mindthegapps

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -39,12 +39,13 @@ on:
             gapps_var:
                 description: "GApps Variant"
                 required: true
-                default: "Full"
+                default: "MindTheGapps"
                 type: choice
                 options:
                     - None
                     - Pico
                     - Full
+                    - MindTheGapps
                     - Custom (OpenGApps)
                     - Custom (MindTheGapps)
             gapps_url:
@@ -119,7 +120,7 @@ jobs:
                   else
                       # TODO: keep it 11.0 since official opengapps does not support 12+ yet
                       # As soon as opengapps is available for 12+, we need to get the sdk/release from build.prop and download the corresponding version
-                      if [[ "${{ inputs.gapps_var }}" == "Full" ]]; then
+                      if [[ "${{ inputs.gapps_var }}" != "None" ]]; then
                           GAPPS_VAR="${opts[GAPPS_VAR,Pico]}"
                       else
                           GAPPS_VAR="${opts[GAPPS_VAR,${{ inputs.gapps_var }}]}"
@@ -127,7 +128,7 @@ jobs:
                   fi
 
                   if [[ "${{ inputs.gapps_var }}" != "None" ]]; then
-                      if [[ "${{ inputs.gapps_var }}" != "Custom (MindTheGapps)" ]]; then
+                      if [[ "${{ inputs.gapps_var }}" != *"MindTheGapps"* ]]; then
                           GAPPS_BRAND="OpenGApps"
                           if [[ "${{ inputs.gapps_var }}" == "Custom (OpenGApps)" ]]; then
                               if [[ -z "${${{ inputs.gapps_url }}+x}" ]]; then
@@ -178,13 +179,18 @@ jobs:
                               fi
                           fi
                       else
-                          echo "${{ inputs.gapps_url }}" > -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"
-
-                          if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_gapps_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -o MindTheGapps-"$ARCH".zip -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"; then
-                              echo "MindTheGapps download error!"
-                              exit 1
-                          fi
+                          GAPPS_VAR="pico"
                           GAPPS_BRAND="MindTheGapps"
+                          if [[ "${{ inputs.gapps_var }}" == "Custom (MindTheGapps)" ]]; then
+                              if [[ -n "${${{ inputs.gapps_url }}+x}" ]]; then
+                                  echo "${{ inputs.gapps_url }}" > -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"
+
+                                  if ! aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_gapps_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity --continue --allow-overwrite --conditional-get -d"$DOWNLOAD_DIR" -o MindTheGapps-"$ARCH".zip -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"; then
+                                      echo "MindTheGapps download error!"
+                                      exit 1
+                                  fi
+                              fi
+                          fi
                       fi
                   else
                       GAPPS_VAR="pico"
@@ -193,7 +199,7 @@ jobs:
 
                   REMOVE_AMAZON="${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}"
 
-                  if [[ "${{ inputs.gapps_var }}" == "Custom (OpenGApps)" ]]; then
+                  if [[ "${{ inputs.gapps_var }}" == "Custom"* ]]; then
                       echo "Generate Download Links"
                       python3 generateWSALinks.py "$ARCH" "$RELEASE_TYPE" "$DOWNLOAD_DIR" "$DOWNLOAD_CONF_NAME"
                       if [[ "${{ inputs.magisk_ver }}" != "Custom" ]]; then
@@ -228,7 +234,7 @@ jobs:
 
                   if [[ "${{ inputs.gapps_var }}" == "None" ]]; then
                       gappsVar=""
-                  elif [[ "${{ inputs.gapps_var }}" == "Custom (MindTheGapps)" ]]; then
+                  elif [[ "${{ inputs.gapps_var }}" == *"MindTheGapps"* ]]; then
                       gappsVar="_MindTheGapps"
                   elif [[ "${{ inputs.gapps_var }}" == "Custom (OpenGApps)" ]]; then
                       gappsVar="_OpenGApps-${{ env.opengapps_var }}"
